import { HeaderSear, SearchSideBar, RestaurantCard } from './components';
import { NarBar } from '../components/';
import { ApiSearch } from '@/helpers/Api';


export const metadata = {
    title: 'Jajajaj',
    description: 'Generated by create next app',
  }
  
export default async function Search({searchParams} : {searchParams: {city:string}}) {

    const [data] = await ApiSearch(searchParams.city)
    
    return (
        <>
            <HeaderSear />
            <div className="flex py-4 m-auto w-2/3 justify-between items-start">
                <SearchSideBar />
                <div className="w-5/6">
                    {
                        data !== undefined ? (
                            data.restaurants.map((res)=>(
                                <RestaurantCard key={res.id} data={res} />
                            ))
                        ) : (<div>No existe restaurant</div>)
                    }
         
                </div>
            </div>
        </>

    )
}