import { Headers } from "../components";
export const metadata = {
    title: 'Que onda',
    description: 'Generated by create next app',
  }
  
export default function RestaurantLayout({
    children,
    params
}: {
    children: React.ReactNode
    params: {slug: string}
}) {
    const {slug} = params
    return (
        <>
            <Headers name={slug} />
            <div className="flex m-auto w-2/3 justify-between items-start 0 -mt-11">
                {children}
            </div>
        </>
    )
}
